(defn constant [h] (fn [a] h))
(defn variable [h] (fn [a] (get a h)))
(defn func [s] (fn [a b] (fn [h] (s (a h) (b h)))))
(def add (func +))
(def subtract (func -))
(def multiply (func *))
(def divide (func (fn [a b] (/ (double a) b))))
(defn negate [a] (fn [h] (- (a h))))
(defn sinh [a] (fn [h] (Math/sinh (a h))))
(defn cosh [a] (fn [h] (Math/cosh (a h))))
(def m {'+ add '- subtract '* multiply '/ divide 'negate negate 'sinh sinh 'cosh cosh})
(defn parseArr [arr] (cond
                       (number? arr) (constant arr)
                       (symbol? arr) (variable (str arr))
                       (== (count arr) 3) ((get m (nth arr 0)) (parseArr (nth arr 1)) (parseArr (nth arr 2)))
                       :else ((get m (nth arr 0)) (parseArr (nth arr 1)))
                       ))
(defn parseFunction [s] (parseArr (read-string s)))

